### PR TITLE
CI: adding minimal build

### PR DESCRIPTION
**Pull request by GitMensch**
as mentioned in [#177](https://github.com/OCamlPro/gnucobol/pull/177#issuecomment-2378725729)

additional:
* added NIST85 summary and duration files to the NIST result artifact
* adjust artifact names to prevent conflicts

### CODE REVIEW

**Review by GitMensch — COMMENTED** [review]
The result LGTM now, so just waiting for a second look.

Note: I haven't checked if we may optimize the long running MSYS workflows (we could, for example, also use the CI tarball generated here, if that helps - but that would need to be a bit adjusted - still possible)

**Review by nberth — APPROVED** [review]
Just in case, I had a quick look as well.

**Comment by ddeclerck** [comment]
Was late on this one, but LGTM ;)

> Note: I haven't checked if we may optimize the long running MSYS workflows (we could, for example, also use the CI tarball generated here, if that helps - but that would need to be a bit adjusted - still possible)

Regarding this issue, it occurs randomly (but often) ; could it be a locking issue ?

**Comment by GitMensch** [comment]
I guess that's a locking issue on the underlying MS Windows OS, if you use multiple jobs it is much more easy to reproduce...

Concerning the other current PR with the build system update ... I've just recognized that most of the appveyor CI is broken now as many seem to run with autoconf 2.69 or older, here it is only the MSYS1 version (which I had expected). So I'll inspect that first...

**Pull request merged**
