### PR TITLE
Fix warnings in GC4

### PR DESCRIPTION
**Pull request by ddeclerck**
@GitMensch Here are my changes to fix the warnings on the GC4 branch. If that's okay I'll commit that to SVN (with an appropriate ChangeLog entry).

### CODE REVIEW

**Comment by GitMensch** [comment]
For the two new files that looks good. For call.c - why don't we have that issue in 3.x?

**Comment by ddeclerck** [comment]
> For the two new files that looks good. For call.c - why don't we have that issue in 3.x?

Actually the problem also occurs in GC3, if you explicitly disable NLS (`configure --disable-nls`). In GC4 the strings where these error occurs are not localized. Makes sense, the truncation analysis can not deduce the size of strings returned by `gettext`.

Maybe you just want to turn this analysis off ?

**Comment by GitMensch** [comment]
OK, if that warning is visible also in 3.x, then commit the changes to the other two files upstream and we can consider this PR finished.

**Comment by ddeclerck** [comment]
> OK, if that warning is visible also in 3.x, then commit the changes to the other two files upstream

Not sure what you want me to do with the third one (`libcob/call.c`) ; should I commit it as well ?

**Comment by GitMensch** [comment]
no, let's inspect that later and have a separate fix (so we can easily merge it)

**Comment by ddeclerck** [comment]
Alright.

Interestingly, the `unsigned` qualifiers were added in a previous commit to solve warnings:
[https://sourceforge.net/p/gnucobol/code/4993/](https://sourceforge.net/p/gnucobol/code/4993/)
My PR actually undoes these changes. Pretty weird.

**Comment by GitMensch** [comment]
oops..

**Comment by GitMensch** [comment]
The fields that are passed to `isspace()` and friends need to stay unsigned.

**Comment by ddeclerck** [comment]
> The fields that are passed to `isspace()` and friends need to stay unsigned.

Indeed, I overlooked this. I'll just add appropriate casts when needed (as suggested by `man`).

**Pull request closed without merging**
