### PR TITLE
[WIP] GNUCobol 3.x with OCamlPro contributions for GCOS

### PR DESCRIPTION
**Pull request by nberth**
The purpose of this branch is to track pending changes, before they are upstreamed

### CODE REVIEW

**Comment by GitMensch** [comment]
I'm still wondering where the deletion of ar-lib and recreation comes from...

BTW: as you've seen - the usptream changes for GCOS support are now also in trunk/master.

**Comment by GitMensch** [comment]
Sadly the CI build does not ship the NIST tests on failure (easiest: just tar the complete tests/cobol85 folder, better: drop all files that have no "log" "out" "txt" "err" extension before) - so one would have to build it locally to check the reason for the DB compile error (a compile error is often easily fixable).

**Comment by GitMensch** [comment]
Hm, where does this go to? Should the branch be updated or this PR closed (and the branch possibly deleted)?

**Comment by lefessan** [comment]
Indeed, this PR was for archival, since some of the work hasn't been upstreamed, but might be useful in the future.

**Comment by GitMensch** [comment]
@nberth @lefessan Is there still any content in that which "hasn't been upstreamed, but might be useful in the future"?
 If not let's delete the branch.

**Pull request closed without merging**
