### PR TITLE
New default-colseq flag to configure program's default COLLATING SEQUENCE

### PR DESCRIPTION
**Pull request by nberth**
In the end this relies more on "alphabets" than "collating sequences", so I'm not sure yet whether the approach is appropriate, or if the option is properly named.

### CODE REVIEW

**Comment by GitMensch** [comment]
I'd say the main question is: should this not be applied in parser.y to base the alphanumeric_collation / default on it?

Or would you in general split file collating sequences (then we'd need a different name)?

And Changelog should likely reference the SF issue.

**Review by GitMensch — APPROVED** [review]
LGTM

**Comment by nberth** [comment]
Now upstream.

@GitMensch I've had two failures for the following two tests (not related to this PR):
- System routines for directories (1)
- System routines for files - filename mapping

Failures appear to be random; one of them also happened on https://ci.appveyor.com/project/GitMensch/gnucobol-3-x/builds/45653125/job/7h019vour18kj9mb

**Comment by GitMensch** [comment]
Thanks for the notice, I've just checked in the fix.

**Pull request closed without merging**
