### PR TITLE
adding gitpod configuration

### PR DESCRIPTION
**Pull request by GitMensch**
this file alone only "prepares" for use of GitPod, but I consider this useful, too

I suggest to additional do the following, after #51:
* possibly register for GitPod, if not done already
* [apply for "Open Source contribution"](https://www.gitpod.io/for/opensource) (effectively upgrading the gratis account to a professional one without costs)
* login and install the app here, see https://github.com/apps/gitpod-io
* configuring [pre-builds](https://www.gitpod.io/docs/prebuilds)

but as noted, that's "optional"; some benefits of GitPod: nice performance, running without costs, _full_ coding and building possible in the browser from anywhere, when pre-builds are active the development can start nearly in an instant, in theory also easy for people to start coding on the project

### CODE REVIEW

**Comment by GitMensch** [comment]
@lefessan @nberth What do you think of this?

A testing _should_ be possible from this URL: https://gitpod.io/#https://github.com/GitMensch/gnucobol-1

(hm, and authorize gitpod, I see that this can be an issue, but maybe you still try that)

**Comment by GitMensch** [comment]
rebased and rechecked, seems fine to me (one _could_ use the vnc base workspace definition to allow running the manual screen tests; but that can be done, later, too

**Comment by GitMensch** [comment]
Juist found out that I've set that to draft months ago... @ddeclerck do you have suggestions compared to the common CI?

**Comment by ddeclerck** [comment]
> Juist found out that I've set that to draft months ago... @ddeclerck do you have suggestions compared to the common CI?

I'm clueless about GitPod...
The proposed configuration seems to "do the job".
Don't know if GitPod allows to upload artifacts (eg. testsuite log) ?

> Would it be reasonable to use the docker you seem to build on/for gitlab? Does it have all the tools installed and is public accessible?

Which docker image are you referring to ?

**Comment by GitMensch** [comment]
> I'm clueless about GitPod...
The proposed configuration seems to "do the job".

With gitpod you don't have any artifact as it opens an online vscode instance connected to a running docker - you have *all* the files ready at hand with the current revision used.

Still - if you have any suggestions then feel free to drop them :-)

> Which docker image are you referring to ?

I've stumbled yesterday over
https://github.com/OCamlPro/gnucobol/blob/21b5d516ffd33e2e25b319680bdcf668b42ff935/.gitlab-ci.yml#L3

Maybe that's something reasonable to use in general, and comes with all the dependencies included?

**Comment by ddeclerck** [comment]
> > I'm clueless about GitPod...
> > The proposed configuration seems to "do the job".
> 
> With gitpod you don't have any artifact as it opens an online vscode instance connected to a running docker - you have _all_ the files ready at hand with the current revision used.
> 
> Still - if you have any suggestions then feel free to drop them :-)

Looks interesting ; I shall give it a try if I find a moment.

> > Which docker image are you referring to ?
> 
> I've stumbled yesterday over
> 
> https://github.com/OCamlPro/gnucobol/blob/21b5d516ffd33e2e25b319680bdcf668b42ff935/.gitlab-ci.yml#L3
> 
> Maybe that's something reasonable to use in general, and comes with all the dependencies included?
> 
> ... self answer when checking further down: the dependencies are installed as pre-script, so reworded question: "Shouldn't those be part of a new image that possibly is based on the other one and includes all dependencies - along with those in the gitpod file here and the ones used in the github ci?"

I wasn't even aware of that GitLab CI 😅. Apparently that was added during early experiments on our internal GitLab instance, before we created the GitHub mirror. The docker image you mention has been made by another team at OCamlPro (I believe it is automatically generated and refreshed from time to time) and is intended for OCaml development. I'd have to check with that team if we can come up with something to use for GnuCOBOL on GitPod.

**Comment by GitMensch** [comment]
@ddeclerck  @lefessan This PR should work as-is already and improve the use of the repo on GitPod. Can you please pull that into the gcos3 and gcos4 branches?

We can come back to adjust this later to care for a possible new base image.
I'll check for the gcos4 one later on as both the CI and the GitPod defintiion should be extended to cater for the multi-io feature.

**Comment by ddeclerck** [comment]
Hi @GitMensch ,
I manually added the configration file to the `gcos4gnucobol-3.x` and `gc4` branches.

**Pull request closed without merging**
